WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f4aba0732b0>: Failed to establish a new connection: 0x04: Host unreachable')': /bot1144928367:AAEHKoUZeDIUVhyZrVo5kzX-5Fq9c7z6IfM/sendMessage
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fc295c2a2b0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot1144928367:AAEHKoUZeDIUVhyZrVo5kzX-5Fq9c7z6IfM/sendMessage
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fc295c2adc0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot1144928367:AAEHKoUZeDIUVhyZrVo5kzX-5Fq9c7z6IfM/sendMessage
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fc295c2a100>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot1144928367:AAEHKoUZeDIUVhyZrVo5kzX-5Fq9c7z6IfM/sendMessage
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fc295bf4970>: Failed to establish a new connection: 0x04: Host unreachable')': /bot1144928367:AAEHKoUZeDIUVhyZrVo5kzX-5Fq9c7z6IfM/sendMessage
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f8523725100>: Failed to establish a new connection: 0x04: Host unreachable')': /bot1144928367:AAEHKoUZeDIUVhyZrVo5kzX-5Fq9c7z6IfM/sendMessage
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f85235a6190>: Failed to establish a new connection: 0x04: Host unreachable')': /bot1144928367:AAEHKoUZeDIUVhyZrVo5kzX-5Fq9c7z6IfM/sendMessage
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f85235a6e80>: Failed to establish a new connection: 0x04: Host unreachable')': /bot1144928367:AAEHKoUZeDIUVhyZrVo5kzX-5Fq9c7z6IfM/sendMessage
ERROR:ex:Bot crashed with an error: Expecting value: line 1 column 1 (char 0)
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fc70f8b02b0>: Failed to establish a new connection: 0x04: Host unreachable')': /bot1144928367:AAEHKoUZeDIUVhyZrVo5kzX-5Fq9c7z6IfM/sendMessage
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fc70f8b0190>: Failed to establish a new connection: 0x04: Host unreachable')': /bot1144928367:AAEHKoUZeDIUVhyZrVo5kzX-5Fq9c7z6IfM/sendMessage
WARNING:telegram.vendor.ptb_urllib3.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fcee12e65e0>: Failed to establish a new connection: 0x04: Host unreachable')': /bot1144928367:AAEHKoUZeDIUVhyZrVo5kzX-5Fq9c7z6IfM/sendMessage
